JSON_DB_CLIENT_CONFIG = "config.json"
JSON_DB_CLIENT_DIR = "clients"
JSON_DB_DATABASE_DIR = "/Users/kerem/Dropbox/software/Tesuji/Parametre/databus/database/json_db"
JSON_DB_LOG_DIR = "log"
JSON_DB_LOG_EXTENSION = "txt"
JSON_DB_QUEUE_ATTACHMENT_DIR = "attachments"
JSON_DB_QUEUE_DIR = "pqueue"
JSON_DB_QUEUE_PASSENGER = "passenger.json"