site_name: Databus
theme: readthedocs
nav:
    - Overview:
        - Home: index.md
        - How it works: how.md
        - Installation: installation.md
        - Startup: startup.md
    - Components:
        - Architecture: architecture.md
        - Database: database.md
        - Client: client.md
        - Dispatcher: dispatcher.md
        - Driver: driver.md
        - Passenger: passenger.md
        - Puller: puller.md
        - Queue: queue.md
        - Processor: processor.md
        - Pusher: pusher.md
        - Web: web.md